ALTER TABLE drive_details ADD status_date TIMESTAMP DEFAULT NOW();

CREATE TABLE IF NOT EXISTS historical_data (
    id SERIAL PRIMARY KEY,
    serial_number text not null,
    drive_model text not null DEFAULT 'unknown',
    drive_status drive_status_enum DEFAULT 'active',
    smart_1_raw INTEGER DEFAULT NULL,
    smart_1_normalized INTEGER DEFAULT NULL,
    smart_4_raw INTEGER DEFAULT NULL,
    smart_4_normalized INTEGER DEFAULT NULL,
    smart_5_raw INTEGER DEFAULT NULL,
    smart_5_normalized INTEGER DEFAULT NULL,
    smart_7_raw INTEGER DEFAULT NULL,
    smart_7_normalized INTEGER DEFAULT NULL,
    smart_9_raw INTEGER DEFAULT NULL,
    smart_9_normalized INTEGER DEFAULT NULL,
    smart_12_raw INTEGER DEFAULT NULL,
    smart_12_normalized INTEGER DEFAULT NULL,
    smart_190_raw INTEGER DEFAULT NULL,
    smart_190_normalized INTEGER DEFAULT NULL,
    smart_192_raw INTEGER DEFAULT NULL,
    smart_192_normalized INTEGER DEFAULT NULL,
    smart_193_raw INTEGER DEFAULT NULL,
    smart_193_normalized INTEGER DEFAULT NULL,
    smart_197_raw INTEGER DEFAULT NULL,
    smart_197_normalized INTEGER DEFAULT NULL,
    smart_198_raw INTEGER DEFAULT NULL,
    smart_198_normalized INTEGER DEFAULT NULL,
    smart_199_raw INTEGER DEFAULT NULL,
    smart_199_normalized INTEGER DEFAULT NULL,
    smart_240_raw INTEGER DEFAULT NULL,
    smart_240_normalized INTEGER DEFAULT NULL,
    smart_241_raw INTEGER DEFAULT NULL,
    smart_241_normalized INTEGER DEFAULT NULL,
    smart_241_cycles real DEFAULT NULL,
    smart_242_raw INTEGER DEFAULT NULL,
    smart_242_normalized INTEGER DEFAULT NULL,
    smart_242_cycles real DEFAULT NULL
);
