ALTER TABLE drive_details ADD status_date TIMESTAMP DEFAULT NOW();

CREATE TABLE IF NOT EXISTS historical_data (
    id SERIAL PRIMARY KEY,
    serial_number text not null,
    drive_model text not null DEFAULT 'unknown',
    drive_status drive_status_enum DEFAULT 'active',
    username text not null,
    smart_1_raw bigint DEFAULT NULL,
    smart_1_normalized bigint DEFAULT NULL,
    smart_4_raw bigint DEFAULT NULL,
    smart_4_normalized bigint DEFAULT NULL,
    smart_5_raw bigint DEFAULT NULL,
    smart_5_normalized bigint DEFAULT NULL,
    smart_7_raw bigint DEFAULT NULL,
    smart_7_normalized bigint DEFAULT NULL,
    smart_9_raw bigint DEFAULT NULL,
    smart_9_normalized bigint DEFAULT NULL,
    smart_12_raw bigint DEFAULT NULL,
    smart_12_normalized bigint DEFAULT NULL,
    smart_190_raw bigint DEFAULT NULL,
    smart_190_normalized bigint DEFAULT NULL,
    smart_192_raw bigint DEFAULT NULL,
    smart_192_normalized bigint DEFAULT NULL,
    smart_193_raw bigint DEFAULT NULL,
    smart_193_normalized bigint DEFAULT NULL,
    smart_197_raw bigint DEFAULT NULL,
    smart_197_normalized bigint DEFAULT NULL,
    smart_198_raw bigint DEFAULT NULL,
    smart_198_normalized bigint DEFAULT NULL,
    smart_199_raw bigint DEFAULT NULL,
    smart_199_normalized bigint DEFAULT NULL,
    smart_240_raw bigint DEFAULT NULL,
    smart_240_normalized bigint DEFAULT NULL,
    smart_241_raw bigint DEFAULT NULL,
    smart_241_normalized bigint DEFAULT NULL,
    smart_241_cycles real DEFAULT NULL,
    smart_242_raw bigint DEFAULT NULL,
    smart_242_normalized bigint DEFAULT NULL,
    smart_242_cycles real DEFAULT NULL
);
